"""Validated product request and response models."""

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, field_validator


class RatingBase(BaseModel):
    """Rating values supplied with product writes."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    rate: Annotated[float, Field(ge=0, le=5, allow_inf_nan=False)]
    count: Annotated[int, Field(ge=0)]


class ProductBase(BaseModel):
    """Product attributes shared by create and update requests."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    title: Annotated[str, Field(min_length=1, max_length=300)]
    price: Annotated[float, Field(gt=0, allow_inf_nan=False)]
    description: Annotated[str, Field(min_length=1, max_length=10_000)]
    category: Annotated[str, Field(min_length=1, max_length=100)]
    image: Annotated[str, Field(max_length=2048)]
    rating: RatingBase

    @field_validator("image")
    @classmethod
    def validate_image_url(cls, value: str) -> str:
        """Accept an empty image or an absolute HTTP(S) URL."""
        if value and not value.startswith(("https://", "http://")):
            raise ValueError("image must be an absolute HTTP(S) URL or an empty string")
        return value


class ProductCreate(ProductBase):
    """Create request; IDs are generated by the database."""


class ProductUpdate(ProductBase):
    """Full replacement update request."""


class RatingResponse(BaseModel):
    """Rating nested in product responses."""

    rate: float
    count: int


class ProductResponse(BaseModel):
    """Public product representation."""

    model_config = ConfigDict(from_attributes=True)

    id: int
    title: str
    price: float
    description: str
    category: str
    image: str
    rating: RatingResponse


class ProductListResponse(BaseModel):
    """Paginated product list with navigation metadata."""

    items: list[ProductResponse]
    total: int
    limit: int
    offset: int


class MessageResponse(BaseModel):
    """Confirmation message returned after a successful operation."""

    message: str


class Problem(BaseModel):
    """RFC 7807 problem detail response."""

    type: str
    title: str
    status: int
    detail: str
    instance: str
    request_id: str
